version: "2.1"

services:
  powerdns-admin:
    build:
      context: .
      dockerfile: docker/PowerDNS-Admin/Dockerfile
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    image: powerdns-admin
    container_name: powerdns-admin
    mem_limit: 256M
    memswap_limit: 256M
    ports:
      - "9191:9191"
    healthcheck:
       test: ["CMD", "curl", "-f", "http://localhost:9191"]
       interval: 30s
       timeout: 5s
       retries: 10
    volumes:
      # Code
      - .:/powerdns-admin/
      - "./configs/${ENVIRONMENT}.py:/powerdns-admin/config.py"
      # Assets dir volume
      - powerdns-admin-assets:/powerdns-admin/app/static
      - powerdns-admin-assets2:/powerdns-admin/node_modules
      - powerdns-admin-assets3:/powerdns-admin/logs
      - ./app/static/custom:/powerdns-admin/app/static/custom
    logging:
      driver: json-file
      options:
        max-size: 50m
    networks:
      - default
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - PDA_DB_HOST=${PDA_DB_HOST}
      - PDA_DB_NAME=${PDA_DB_NAME}
      - PDA_DB_USER=${PDA_DB_USER}
      - PDA_DB_PASSWORD=${PDA_DB_PASSWORD}
      - PDA_DB_PORT=${PDA_DB_PORT}
#
      - PDA_PGDB_HOST=${PDA_PGDB_HOST}
      - PDA_PGDB_NAME=${PDA_PGDB_NAME}
      - PDA_PGDB_USER=${PDA_PGDB_USER}
      - PDA_PGDB_PASSWORD=${PDA_PGDB_PASSWORD}
      - PDA_PGDB_PORT=${PDA_PGDB_PORT}
#      
      - PDNS_PROTO=${PDNS_PROTO}
      - PDNS_PORT=${PDNS_PORT}
      - PDNS_HOST=${PDNS_HOST}
      - PDNS_API_KEY=${PDNS_API_KEY}
      - FLASK_APP=/powerdns-admin/app/__init__.py
    depends_on:
      - pdns-postgres
#    depends_on:
#      powerdns-admin-mysql:
#        condition: service_healthy

#  powerdns-admin-mysql:
#    image: mysql/mysql-server:5.7
#    hostname: ${PDA_DB_HOST}
#    container_name: powerdns-admin-mysql
#    mem_limit: 256M
#    memswap_limit: 256M
#    expose:
#      - 3306
#    volumes:
#      - powerdns-admin-mysql-data:/var/lib/mysql
#    networks:
#      - default
#    environment:
#      - MYSQL_DATABASE=${PDA_DB_NAME}
#      - MYSQL_USER=${PDA_DB_USER}
#      - MYSQL_PASSWORD=${PDA_DB_PASSWORD}
#    healthcheck:
#      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
#      timeout: 10s
#      retries: 5

  pdns-server:
    image: milekz/docker-powerdns
    hostname: ${PDNS_HOST}
    ports:
      - "53:53"
      - "53:53/udp"
      - "8081:8081"
    networks:
      - default
    command: --api=yes --api-key=${PDNS_API_KEY} --webserver-address=0.0.0.0 --webserver-allow-from=0.0.0.0/0
    environment:
#      - MYSQL_HOST=${PDNS_DB_HOST}
#      - MYSQL_USER=${PDNS_DB_USER}
#      - MYSQL_PASS=${PDNS_DB_PASSWORD}
      - PGSQL_HOST=${PDNS_PGDB_HOST}
      - PGSQL_USER=${PDNS_PGDB_USER}
      - PGSQL_PASS=${PDNS_PGDB_PASSWORD}
      - PDNS_API_KEY=${PDNS_API_KEY}
      - PDNS_WEBSERVER_ALLOW_FROM=${PDNS_WEBSERVER_ALLOW_FROM}
    depends_on:
      - pdns-postgres
#        condition: service_healthy

#  pdns-mysql:
#    image: mysql/mysql-server:5.7
#    hostname: ${PDNS_DB_HOST}
#    container_name: ${PDNS_DB_HOST}
#    mem_limit: 256M
#    memswap_limit: 256M
#    expose:
#      - 3306
#    volumes:
#      - powerdns-mysql-data:/var/lib/mysql
#    networks:
#      - default
#    environment:
#      - MYSQL_DATABASE=${PDNS_DB_NAME}
#      - MYSQL_USER=${PDNS_DB_USER}
#      - MYSQL_PASSWORD=${PDNS_DB_PASSWORD}
#    healthcheck:
#      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
#      timeout: 10s
#      retries: 5

  pdns-postgres:
     image: postgres:11-alpine
     hostname: ${PDNS_PGDB_HOST}
     container_name: ${PDNS_PGDB_HOST}
     volumes:
        - powerdns-postgres-data:/var/lib/postgresql/data/
        - ./db_schema:/docker-entrypoint-initdb.d/
     restart: always
     ports:
        - "5432:5432"
     environment:
        - POSTGRES_PASSWORD=${PDNS_PGDB_PASSWORD}
        - PGSQL_DBNAME=${PDNS_PGDB_NAME}
        - PGSQL_USER=${PDNS_PGDB_USER}
        - PGSQL_PASS=${PDNS_PGDB_PASSWORD}
        - PDA_PGDB_DBNAME=${PDA_PGDB_NAME}
        - PDA_PGDB_USER=${PDA_PGDB_USER}
        - PDA_PGDB_PASS=${PDA_PGDB_PASSWORD}
#
        - PDNS_PGDB_REPLICA_PASSWORD=${PDNS_PGDB_REPLICA_PASSWORD}
        - PDNS_PGDB_REPLICA_USER=${PDNS_PGDB_REPLICA_USER}
                                      
                                      
networks:
  default:

volumes:
  powerdns-mysql-data:
  powerdns-admin-mysql-data:
  powerdns-admin-assets:
  powerdns-admin-assets2:
  powerdns-admin-assets3:
  powerdns-postgres-data:
  